//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetspeedMainWebsite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://online.netspeed.com.tr")]
        public string oimUrl {
            get {
                return ((string)(this["oimUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MailUseSSL {
            get {
                return ((bool)(this["MailUseSSL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int MailHostPort {
            get {
                return ((int)(this["MailHostPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mail.netspeed.com.tr")]
        public string MailHostName {
            get {
                return ((string)(this["MailHostName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("testwebservice")]
        public string WebServiceUsername {
            get {
                return ((string)(this["WebServiceUsername"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12345678")]
        public string WebServicePasswordHash {
            get {
                return ((string)(this["WebServicePasswordHash"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:02:00")]
        public global::System.TimeSpan SMSValidationDuration {
            get {
                return ((global::System.TimeSpan)(this["SMSValidationDuration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6LemlQwaAAAAAMAzZ6gkJsOT6eFTMOdu5xWO8r5X")]
        public string CaptchaSecretKey {
            get {
                return ((string)(this["CaptchaSecretKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6LemlQwaAAAAAFqlAuPzuuBF-gF0HrNBeelSS2xJ")]
        public string CaptchaSiteKey {
            get {
                return ((string)(this["CaptchaSiteKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sozlesmetest@netspeed.com.tr")]
        public string MailUsernameNetspeed {
            get {
                return ((string)(this["MailUsernameNetspeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("beniara@netspeed.com.tr")]
        public string MailReceiverNetspeed {
            get {
                return ((string)(this["MailReceiverNetspeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JUpc47E0")]
        public string MailPasswordNetspeed {
            get {
                return ((string)(this["MailPasswordNetspeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("noreply@netspeed.com.tr")]
        public string MailDisplayEmail {
            get {
                return ((string)(this["MailDisplayEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Netspeed Beni Ara Talebi")]
        public string MailDisplayName {
            get {
                return ((string)(this["MailDisplayName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<span style=\'color:green;\' class=\'h4\'>Ödenmemiş faturanız bulunmamaktadır.</span>" +
            "")]
        public string UnpaidBillsNotFoundMessage {
            get {
                return ((string)(this["UnpaidBillsNotFoundMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<span style=\'color:red;\' class=\'h4\'>Aboneliğiniz bu işlem için uygun değil. Onlin" +
            "e işlem merkezi üzerinden ödemenizi yapabilirsiniz.</span>")]
        public string BillHaveMoreSubscriptionMessage {
            get {
                return ((string)(this["BillHaveMoreSubscriptionMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<div class=""alert alert-custom alert-danger fade show"" role=""alert"">
    <div class=""alert-icon""><i class="" display-3  flaticon-warning""></i></div>
    <div class=""font-size-h5 alert-text"">Üzgünüz! Adresinizde Altyapı veya Boş Port Bulunamadığından Başvurunuza Devam. Edemiyoruz</div>
    <div class=""alert-close"">
        <button type=""button"" class=""close"" data-dismiss=""alert"" aria-label=""Close"">
            <span aria-hidden=""true""><i class=""ki ki-close""></i></span>
        </button>
    </div>
</div>")]
        public string ExternalTariffErrorMessage {
            get {
                return ((string)(this["ExternalTariffErrorMessage"]));
            }
        }
    }
}
